home/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_view

app_name = 'study'

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('room/<pk>/detail', views.RoomDetailView.as_view(), name='room'),
    path('signup/', views.SignUp.as_view(), name='signup'),
    path('login/', auth_view.LoginView.as_view(template_name='home/login.html', redirect_authenticated_user=True), name='login'),
    path('logout', auth_view.LogoutView.as_view(next_page='study:login'), name='logout'),
    path('room/browse-topics/', views.BrowseTopics.as_view(), name='browse_topics'),
    path('profile/<int:user_id>/', views.ProfileView.as_view(), name='profile'),
    path('room/create/', views.CreateRoomView.as_view(), name='create_room'),
    path('message/<pk>/delete', views.DeleteCommentView.as_view(), name='delete_message'),
    path('profile/<int:pk>/update', views.UpdateProfile.as_view(), name='update_profile'),
]

studybudd/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

home/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse_lazy
# Create your models here.


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    avatar = models.ImageField(upload_to='profile_images', blank=True, default='default.jpg')
    about = models.TextField(max_length=700, default="")

    def __str__(self):
        return self.user.username


class Topic(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name


class Room(models.Model):
    host = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    topic = models.ForeignKey(Topic, on_delete=models.SET_NULL, null=True)
    name = models.CharField(max_length=200)
    description = models.TextField(null=True, blank=True)
    participants = models.ManyToManyField(
        User, related_name='participants', blank=True)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-updated', '-created']

    def get_absolute_url(self):
        return reverse_lazy('study:room', kwargs={'pk': self.pk})

    def __str__(self):
        return self.name


class Message(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    room = models.ForeignKey(Room, on_delete=models.CASCADE, related_name='messages')
    body = models.CharField(max_length=400, help_text='your messages here'
    )
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-updated', '-created']

    def __str__(self):
        return self.body[0:50]

home/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import UserProfile, Message, Room


class CreateUser(UserCreationForm):
    email = forms.EmailField()
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']


class UpdateProfileForm(forms.ModelForm):
    first_name = forms.CharField(max_length=20)
    last_name = forms.CharField(max_length=20)
    username = forms.CharField(max_length=20)
    email = forms.EmailField()
    avatar = forms.ImageField()

    class Meta(User):
        model = UserProfile
        fields = ['avatar', 'first_name', 'last_name', 'username', 'email', 'about']


class CommentForm(forms.ModelForm):

    class Meta:
        model = Message
        fields = ['body']

class CreateRoomForm(forms.ModelForm):
    class Meta:
        model = Room
        fields = ['topic', 'name', 'description']

home/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.db.models import Q
from django.views import View
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from .forms import CreateUser, CommentForm, CreateRoomForm, UpdateProfileForm
from .models import UserProfile, Topic, Room, Message
from urllib.parse import unquote
from django.utils.html import escape
from django.contrib.auth.models import User


# we can do it like this, or we can define another view (for the rest like routing) and another url
# like: this/param/ and we have to pass the parameter in the url to the function/class in the views.
# class HomeFilterView(LoginRequiredMixin, View):
#     login_url = reverse_lazy('study:login')
#     model = Room
#     template_name = 'home/index.html'
#
#     def get(self, request, filter):
#         rooms = self.model.objects.filter(
#             Q(topic__name__icontains=filter) |
#             Q(name__icontains=filter) |
#             Q(host__username__icontains=filter)
#         )
#         topics = Topic.objects.all()
#         messages = Message.objects.filter(room__in=rooms).all()
#         context = {'room_list': rooms, 'topics': topics, 'messages': messages}
#         return render(request, self.template_name, context)
# in this case we may have some special characters like # in c# # is called fragment identifier, the browser
# will not send anything after it. so to bypass it we have to encode using urlencode filter in out template
# and decode it in our backend also we have to escape it to prevent xss atacks

class HomeView(LoginRequiredMixin, View):
    model = Room
    template_name = 'home/index.html'

    def get(self, request):
        q = escape(unquote(self.request.GET.get('q'))) if request.GET.get('q') else ''
        rooms = Room.objects.filter(
            Q(topic__name__icontains=q) |
            Q(name__icontains=q) |
            Q(host__username__icontains=q)
        )
        topics = Topic.objects.all()
        messages = Message.objects.filter(room__in=rooms)
        context = {'room_list': rooms, 'messages': messages, 'topics': topics}
        return render(request, self.template_name, context)


class SignUp(SuccessMessageMixin, CreateView):
    form_class = CreateUser
    success_url = reverse_lazy('study:login')
    template_name = 'home/signup.html'
    success_message = "%(username)s was created successfully"


class BrowseTopics(LoginRequiredMixin, View):
    model = Topic
    template_name = 'home/topics.html'

    def get(self, request):
        q = escape(unquote(self.request.GET.get('q'))) if request.GET.get('q') else ''
        context = {'topic_list': self.model.objects.filter(Q(name__icontains=q))}
        return render(request, self.template_name, context)


class ProfileView(LoginRequiredMixin, View):
    template_name = 'home/profile.html'

    def get(self, request, user_id):
        context = {
            'profile': get_object_or_404(UserProfile, user=user_id),
            'topics': Topic.objects.all(),
            'rooms': Room.objects.filter(host=user_id),
            'messages': Message.objects.filter(user_id=user_id),
        }
        return render(request, self.template_name, context)


class CreateRoomView(LoginRequiredMixin, View):
    template_name = 'home/create-room.html'

    def get(self, request):
        context = {'form': CreateRoomForm()}
        return render(request, self.template_name, context)

    def post(self, request):
        topic_id = request.POST.get('topic')
        topic, create = Topic.objects.get_or_create(id=topic_id)
        print(topic)
        room, is_created = Room.objects.get_or_create(
            host=request.user,
            topic=topic,
            name=request.POST.get('name'),
            description=request.POST.get('description'),
        )
        room.participants.add(request.user)
        return redirect(reverse_lazy('study:home'))


class RoomDetailView(LoginRequiredMixin, View):
    model = Room

    def get(self, request, pk):
        context = {
            'room': get_object_or_404(self.model, pk=pk),
            'form': CommentForm(),
        }
        return render(request, 'home/room.html', context)

    def post(self, request, pk):
        form = CommentForm(request.POST)
        if form.is_valid():
            form.instance.user = request.user
            form.instance.room_id = pk
            form.save()
            return redirect(reverse_lazy('study:room', kwargs={'pk': pk}))
        return self.get(request, pk)


class DeleteCommentView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Message
    success_url = reverse_lazy('study:home')
    template_name = 'home/delete-comment.html'

    def test_func(self):
        message = self.get_object()
        return True if message.user == self.request.user else False


class UpdateProfile(LoginRequiredMixin, View):
    model = UserProfile
    template_name = 'home/edit-user.html'

    def get(self, request, pk):
        profile = get_object_or_404(self.model, pk=pk, user=request.user)
        form = UpdateProfileForm(
            initial={
                'first_name': profile.user.first_name,
                'last_name': profile.user.last_name,
                'username': profile.user.username,
                'email': profile.user.email,
                'about': profile.about
            })
        context = {'form': form}
        return render(request, self.template_name, context)

    def post(self, request, pk):
        profile = get_object_or_404(UserProfile, pk=pk)
        form = UpdateProfileForm(request.POST, request.FILES, instance=profile)
        if form.is_valid():
            form.save()
            return redirect(reverse_lazy('study:profile', kwargs={'user_id': profile.user.id}))

        context = {'form': form}
        return render(request, self.template_name, context)

home/templates/home/activity_component.html
  <div class="activities">
          <div class="activities__header">
            <h2>Recent Activities</h2>
          </div>
      {% for message in messages %}
          <div class="activities__box">
            <div class="activities__boxHeader roomListRoom__header">
              <a href="profile.html" class="roomListRoom__author">
                <div class="avatar avatar--small">
                  <img src="https://randomuser.me/api/portraits/women/11.jpg" />
                </div>
                <p>
              <!--       comment owner           -->
                  @{{ message.user.username }}
                  <span>{{ message.created }} </span>
                </p>
              </a>
                {% if message.user == user %}
              <div class="roomListRoom__actions">
                <a href="{% url 'study:delete_message' message.id %}">
                  <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                    <title>remove</title>
                    <path
                      d="M27.314 6.019l-1.333-1.333-9.98 9.981-9.981-9.981-1.333 1.333 9.981 9.981-9.981 9.98 1.333 1.333 9.981-9.98 9.98 9.98 1.333-1.333-9.98-9.98 9.98-9.981z"
                    ></path>
                  </svg>
                </a>
              </div>
              {% endif %}
            </div>

            <div class="activities__boxContent">
              <p>replied to post “<a href="room.html">{{message.room.name}}</a>”</p>
              <div class="activities__boxRoomContent">
                  {{message.body| truncatechars:50 }}
              </div>
            </div>
          </div>
  {% endfor %}

</div>

home/templates/home/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="shortcut icon" href="{% static 'home/assets/favicon.ico' %}" type="image/x-icon" />
    <link rel="stylesheet" href="{% static 'home/css/styles.css' %}" />
    <title>StudyBuddy - Find study partners around the world!</title>
  </head>

  <body>
    <header class="header header--loggedIn">
      <div class="container">
        <a href="/" class="header__logo">
          <img src="{% static 'home/assets/logo.svg' %}" />
          <h1>StudyBuddy</h1>
        </a>
        <form class="header__search" method="get">
          <label>
            <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
              <title>search</title>
              <path
                d="M32 30.586l-10.845-10.845c1.771-2.092 2.845-4.791 2.845-7.741 0-6.617-5.383-12-12-12s-12 5.383-12 12c0 6.617 5.383 12 12 12 2.949 0 5.649-1.074 7.741-2.845l10.845 10.845 1.414-1.414zM12 22c-5.514 0-10-4.486-10-10s4.486-10 10-10c5.514 0 10 4.486 10 10s-4.486 10-10 10z"
              ></path>
            </svg>
            {% url 'study:home' as path %}
            {% if request.path == path %}
            <input placeholder="Search for rooms..." name="q" />
            {% else %}
            <input placeholder="Search for posts" name="q"/>
            {% endif %}
          </label>
        </form>
        <nav class="header__menu">
          <!-- Not Logged In -->
          {% if not user.is_authenticated %}
          <a href="/login.html">
            <img src="{% static 'home/assets/avatar.svg' %}" />
            <p>Login</p>
          </a>


          <!-- Logged In -->
          {% else %}
          <div class="header__user">
            <a href="{% url 'study:profile' user.id %}">
              <div class="avatar avatar--medium active">
                <img src="{{  user.userprofile.avatar.url }}" />
              </div>
              <p>{{ user.first_name}} {{ user.last_name }}  <span>@{{ user.username }}</span></p>
            </a>
            <button class="dropdown-button">
              <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                <title>chevron-down</title>
                <path d="M16 21l-13-13h-3l16 16 16-16h-3l-13 13z"></path>
              </svg>
            </button>
          </div>
          {% endif %}
    <!-- ==================================================        -->
    {% if user.is_authenticated %}
          <div class="dropdown-menu">
            <a href="{% url 'study:profile' user.id %}" class="dropdown-link"
              ><svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                <title>tools</title>
                <path
                  d="M27.465 32c-1.211 0-2.35-0.471-3.207-1.328l-9.392-9.391c-2.369 0.898-4.898 0.951-7.355 0.15-3.274-1.074-5.869-3.67-6.943-6.942-0.879-2.682-0.734-5.45 0.419-8.004 0.135-0.299 0.408-0.512 0.731-0.572 0.32-0.051 0.654 0.045 0.887 0.277l5.394 5.395 3.586-3.586-5.394-5.395c-0.232-0.232-0.336-0.564-0.276-0.887s0.272-0.596 0.572-0.732c2.552-1.152 5.318-1.295 8.001-0.418 3.274 1.074 5.869 3.67 6.943 6.942 0.806 2.457 0.752 4.987-0.15 7.358l9.392 9.391c0.844 0.842 1.328 2.012 1.328 3.207-0 2.5-2.034 4.535-4.535 4.535zM15.101 19.102c0.26 0 0.516 0.102 0.707 0.293l9.864 9.863c0.479 0.479 1.116 0.742 1.793 0.742 1.398 0 2.535-1.137 2.535-2.535 0-0.668-0.27-1.322-0.742-1.793l-9.864-9.863c-0.294-0.295-0.376-0.74-0.204-1.119 0.943-2.090 1.061-4.357 0.341-6.555-0.863-2.631-3.034-4.801-5.665-5.666-1.713-0.561-3.468-0.609-5.145-0.164l4.986 4.988c0.391 0.391 0.391 1.023 0 1.414l-5 5c-0.188 0.188-0.441 0.293-0.707 0.293s-0.52-0.105-0.707-0.293l-4.987-4.988c-0.45 1.682-0.397 3.436 0.164 5.146 0.863 2.631 3.034 4.801 5.665 5.666 2.2 0.721 4.466 0.604 6.555-0.342 0.132-0.059 0.271-0.088 0.411-0.088z"
                ></path>
              </svg>
              Settings </a>
            <a href="{% url 'study:logout' %} " class="dropdown-link"
              ><svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                <title>sign-out</title>
                <path
                  d="M3 0h22c0.553 0 1 0 1 0.553l-0 3.447h-2v-2h-20v28h20v-2h2l0 3.447c0 0.553-0.447 0.553-1 0.553h-22c-0.553 0-1-0.447-1-1v-30c0-0.553 0.447-1 1-1z"
                ></path>
                <path
                  d="M21.879 21.293l1.414 1.414 6.707-6.707-6.707-6.707-1.414 1.414 4.293 4.293h-14.172v2h14.172l-4.293 4.293z"
                ></path>
              </svg>
              Logout</a>
          </div>
          {% endif %}
        </nav>
      </div>
    </header>

  {% block content %} {% endblock content %}

   </main>
    <script src=" {% static 'home/js/script.js' %}"></script>
  </body>
</html>

home/templates/home/create-room.html
{% extends 'home/base.html' %}
{% block content %}

  <main class="create-room layout">
    <div class="container">
      <div class="layout__box">
        <div class="layout__boxHeader">
          <div class="layout__boxTitle">
            <a href="index.html">
              <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                <title>arrow-left</title>
                <path
                  d="M13.723 2.286l-13.723 13.714 13.719 13.714 1.616-1.611-10.96-10.96h27.625v-2.286h-27.625l10.965-10.965-1.616-1.607z">
                </path>
              </svg>
            </a>
            <h3>Create Study Room</h3>
          </div>
        </div>
        <div class="layout__body">
          <form class="form" method="post">
            {% csrf_token %}
            <div class="form__group">
              <label for="room_name">Room Name</label>
              {{form.name}}
            </div>

            <div class="form__group">
              <label for="room_topic">Topic</label>
              {{form.topic}}
              </datalist>
            </div>


            <div class="form__group">
              <label for="room_about">About</label>
             {{ form.description }}
            </div>
            <div class="form__action">
              <a class="btn btn--dark" href="{% url 'study:home' %}">Cancel</a>
              <button class="btn btn--main" type="submit">Create Room</button>
            </div>
          </form>
        </div>
      </div>
    </div>
     </main>
{% endblock content %}

home/templates/home/index.html
{% extends 'home/base.html' %}
{% load humanize %}

{% block content %}
    <main class="layout layout--3">
      <div class="container">
        <!-- Topics Start -->
      {% include 'home/topic_component.html' %}
        <!-- Topics End -->

        <!-- Room List Start -->
        <div class="roomList">
          <div class="mobile-menu">
            <form class="header__search" method="get">
              <label>
                 <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                  <title>search</title>
                  <path
                    d="M32 30.586l-10.845-10.845c1.771-2.092 2.845-4.791 2.845-7.741 0-6.617-5.383-12-12-12s-12 5.383-12 12c0 6.617 5.383 12 12 12 2.949 0 5.649-1.074 7.741-2.845l10.845 10.845 1.414-1.414zM12 22c-5.514 0-10-4.486-10-10s4.486-10 10-10c5.514 0 10 4.486 10 10s-4.486 10-10 10z"
                  ></path>
                </svg>
                <input placeholder="Search for posts" />
              </label>
            </form>
            <div class="mobile-menuItems">
              <a class="btn btn--main btn--pill" href="#">Browse Topics</a>
              <a class="btn btn--main btn--pill" href="#">Recent Activities</a>
            </div>
          </div>
        <!--  create room     -->
          <div class="roomList__header">
            <div>
              <h2>Study Room</h2>
              <p>{{ room_list.count}} Rooms available</p>
            </div>
            <a class="btn btn--main" href="{% url 'study:create_room' %}">
              <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                <title>add</title>
                <path
                  d="M16.943 0.943h-1.885v14.115h-14.115v1.885h14.115v14.115h1.885v-14.115h14.115v-1.885h-14.115v-14.115z"
                ></path>
              </svg>
              Create Room
            </a>
          </div>

        <!-- room listings          -->
          {% if room_list %}
            {% for room in room_list %}
              <div class="roomListRoom">
            <div class="roomListRoom__header">
              <a href="{% url 'study:profile' room.host.id %}" class="roomListRoom__author">
                <div class="avatar avatar--small">
                  <img src="{{room.host.userprofile.avatar.url}}" />
                </div>
            <!-- host -->
                <span>@{{ room.host.username }}</span>
              </a>
              <div class="roomListRoom__actions">
                <span>{{ room.updated | naturaltime }} </span>
              </div>
            </div>
            <div class="roomListRoom__content">
              <a href="{% url 'study:room' room.id %}">{{room.name}}</a>
              <p>
                {{ room.description }}
              </p>
            </div>
            <div class="roomListRoom__meta">
              <a href="{% url 'study:room' room.id %}" class="roomListRoom__joined">
                <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                  <title>user-group</title>
                  <path
                    d="M30.539 20.766c-2.69-1.547-5.75-2.427-8.92-2.662 0.649 0.291 1.303 0.575 1.918 0.928 0.715 0.412 1.288 1.005 1.71 1.694 1.507 0.419 2.956 1.003 4.298 1.774 0.281 0.162 0.456 0.487 0.456 0.85v4.65h-4v2h5c0.553 0 1-0.447 1-1v-5.65c0-1.077-0.56-2.067-1.461-2.584z"
                  ></path>
                  <path
                    d="M22.539 20.766c-6.295-3.619-14.783-3.619-21.078 0-0.901 0.519-1.461 1.508-1.461 2.584v5.65c0 0.553 0.447 1 1 1h22c0.553 0 1-0.447 1-1v-5.651c0-1.075-0.56-2.064-1.461-2.583zM22 28h-20v-4.65c0-0.362 0.175-0.688 0.457-0.85 5.691-3.271 13.394-3.271 19.086 0 0.282 0.162 0.457 0.487 0.457 0.849v4.651z"
                  ></path>
                  <path
                    d="M19.502 4.047c0.166-0.017 0.33-0.047 0.498-0.047 2.757 0 5 2.243 5 5s-2.243 5-5 5c-0.168 0-0.332-0.030-0.498-0.047-0.424 0.641-0.944 1.204-1.513 1.716 0.651 0.201 1.323 0.331 2.011 0.331 3.859 0 7-3.141 7-7s-3.141-7-7-7c-0.688 0-1.36 0.131-2.011 0.331 0.57 0.512 1.089 1.075 1.513 1.716z"
                  ></path>
                  <path
                    d="M12 16c3.859 0 7-3.141 7-7s-3.141-7-7-7c-3.859 0-7 3.141-7 7s3.141 7 7 7zM12 4c2.757 0 5 2.243 5 5s-2.243 5-5 5-5-2.243-5-5c0-2.757 2.243-5 5-5z"
                  ></path>
                </svg>
                {{room.participants.count}}
              </a>
              <p class="roomListRoom__topic">{{room.topic.name}}</p>
            </div>
              </div>
            {% endfor %}
          {% else %}
            <h2>No rooms found</h2>
          {% endif %}
        </div>
        <!-- Room List End -->
        <!-- Activities Start -->
      {% include 'home/activity_component.html' %}
        <!-- Activities End -->
      </div>
    </main>
{% endblock content %}

home/templates/home/profile.html
{% extends 'home/base.html' %}
{% load humanize %}
{% block content %}

  <main class="profile-page layout layout--3">
    <div class="container">
      <!-- Topics Start -->
      {% include 'home/topic_component.html' %}
      <!-- Topics End -->

      <!-- Room List Start -->
      <div class="roomList">
        <div class="profile">
          <div class="profile__avatar">
            <div class="avatar avatar--large active">
              <img src="{{ profile.avatar.url }}" />
            </div>
          </div>
          <div class="profile__info">
            <h3>{{ profile.user.first_name}} {{ profile.user.last_name}}</h3>
            <p>@{{ profile.user.username }}</p>

            {% if request.user == profile.user %}
            <a href="{% url 'study:update_profile' profile.id %}" class="btn btn--main btn--pill">Edit Profile</a>
            {% endif %}
          </div>
          <div class="profile__about">
            <h3>About</h3>
            <p>
              {{ profile.about }}
            </p>
          </div>
        </div>

      <!--       room lists        -->
        <div class="roomList__header">
          <div>
            <h2>Study Rooms Hosted by {{ profile.user.username }}</a>
            </h2>
          </div>
        </div>
        {% if rooms %}
        {% for room in rooms %}
        <div class="roomListRoom">
          <div class="roomListRoom__header">
            <a href="{% url 'study:profile' user.id %}" class="roomListRoom__author">
              <div class="avatar avatar--small active">
                <img src="{{ room.host.userprofile.url }}" />
              </div>
              <span>@{{ profile.user.username }}</span>
            </a>
            <div class="roomListRoom__actions">
              <span>{{ room.created|naturaltime }}</span>

            </div>
          </div>
          <div class="roomListRoom__content">
            <a href="{% url 'study:room' room.id %}"> {{ room.name}}</a>
            <p>
              {{room.description}}
            </p>
          </div>
          <div class="roomListRoom__meta">
            <a class="roomListRoom__joined">
              <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                <title>user-group</title>
                <path
                  d="M30.539 20.766c-2.69-1.547-5.75-2.427-8.92-2.662 0.649 0.291 1.303 0.575 1.918 0.928 0.715 0.412 1.288 1.005 1.71 1.694 1.507 0.419 2.956 1.003 4.298 1.774 0.281 0.162 0.456 0.487 0.456 0.85v4.65h-4v2h5c0.553 0 1-0.447 1-1v-5.65c0-1.077-0.56-2.067-1.461-2.584z">
                </path>
                <path
                  d="M22.539 20.766c-6.295-3.619-14.783-3.619-21.078 0-0.901 0.519-1.461 1.508-1.461 2.584v5.65c0 0.553 0.447 1 1 1h22c0.553 0 1-0.447 1-1v-5.651c0-1.075-0.56-2.064-1.461-2.583zM22 28h-20v-4.65c0-0.362 0.175-0.688 0.457-0.85 5.691-3.271 13.394-3.271 19.086 0 0.282 0.162 0.457 0.487 0.457 0.849v4.651z">
                </path>
                <path
                  d="M19.502 4.047c0.166-0.017 0.33-0.047 0.498-0.047 2.757 0 5 2.243 5 5s-2.243 5-5 5c-0.168 0-0.332-0.030-0.498-0.047-0.424 0.641-0.944 1.204-1.513 1.716 0.651 0.201 1.323 0.331 2.011 0.331 3.859 0 7-3.141 7-7s-3.141-7-7-7c-0.688 0-1.36 0.131-2.011 0.331 0.57 0.512 1.089 1.075 1.513 1.716z">
                </path>
                <path
                  d="M12 16c3.859 0 7-3.141 7-7s-3.141-7-7-7c-3.859 0-7 3.141-7 7s3.141 7 7 7zM12 4c2.757 0 5 2.243 5 5s-2.243 5-5 5-5-2.243-5-5c0-2.757 2.243-5 5-5z">
                </path>
              </svg>
              {{room.participants.count}}
            </a>
            <p class="roomListRoom__topic">{{room.topic}}</p>
          </div>
        </div>
        {% endfor %}
        {% else %}
        <p><a href="{% url 'study:create_room' %}">Create a Room</a> </p>
        {% endif %}
      </div>
      <!-- Room List End -->

      <!-- Activities Start -->
      {% include 'home/activity_component.html' %}
      <!-- Activities End -->
    </div>
  </main>
{% endblock content %}

home/templates/home/topic_component.html
        <div class="topics">
          <div class="topics__header">
            <h2>Browse Topics</h2>
          </div>
          <ul class="topics__list">
            <li>
              <a href="/" class="active">All <span>{{topics.count }}</span></a>
            </li>
              {% for topic in topics %}
            <li>
              <a href="{% url 'study:home' %}?q={{ topic.name|urlencode }}">{{ topic.name }} <span>{{ topic.room_set.count }}</span></a>
            </li>
           {% endfor %}
          </ul>
          <a class="btn btn--link" href="{% url 'study:browse_topics' %}">
            More
            <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
              <title>chevron-down</title>
              <path d="M16 21l-13-13h-3l16 16 16-16h-3l-13 13z"></path>
            </svg>
          </a>
        </div>